### ISSUE TITLE
Error: Expected an opening square bracket.

### ISSUE THREAD

**Issue by foxted** [tailwindui/issues#134]
**Describe the bug**

I am using @nuxtjs/tailwindcss plugin in my app. I tried adding the `@tailwindcss/ui` plugin like the docs suggest in `tailwind.config.js`, but now when building the project, I get this error: 

```

ERROR in ./app/assets/css/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./app/assets/css/tailwind.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Expected an opening square bracket.
    at /Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/tailwindcss/utilities.css:1:1
    at Root._error (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:137:24)
    at Root.error (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/selectors/root.js:43:25)
    at Parser.error (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:392:25)
    at Parser.expected (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:685:25)
    at Parser.missingSquareBracket (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:406:21)
    at Parser.parse (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:668:22)
    at Parser.loop (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:618:18)
    at new Parser (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:129:14)
    at Processor._root (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:47:22)
    at Processor._runSync (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:83:25)
    at Processor.processSync (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:177:27)
    at getParsed (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/dist/index.js:34:59)
    at /Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss-minify-selectors/dist/index.js:196:39
    at /Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss/lib/container.js:239:18
    at /Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss/lib/container.js:135:18
    at AtRule.each (/Users/valentinprugnaud/Sites/Speakbox/speakbox-web-app/node_modules/postcss/lib/container.js:101:16)
 @ ./app/assets/css/tailwind.css 4:14-172
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

**To Reproduce**
1. Create an app with @nuxtjs and @nuxtjs/tailwindcss plugin
2. Add @tailwindcss/ui plugin
3. Run `nuxt generate`

**Expected behavior**

Expected to compile normally. 

**Browser/Device (if applicable)**
 - OS: macOS Catalina 10.15.3
 - Browser: N/A
 - Version: N/A

**Additional context**

Created another issue on the @nuxtjs/tailwind project as well: https://github.com/nuxt-community/tailwindcss-module/issues/79

**Comment by tealendril** [comment]
Can confirm, 
`@tailwindcss/ui plugin` breaks build/generate on nuxt.js

`@nuxtjs/tailwindcss` is not part of the issue, building without it causes the same error.

**Comment by adamwathan** [comment]
The problem is a bug in postcss preset env which has been fixed but not tagged, and nuxt enables that plugin invisibly by default (kind of bad behaviour in my opinion because it leads to hard to troubleshoot issues like this.)

If you disable the focus within feature of postcss preset env you should be good to go.

**Comment by Atinux** [comment]
See how to fix the issue in Nuxt: https://github.com/nuxt-community/tailwindcss-module/issues/79#issuecomment-609693459

I hope that the postcss present env fix will be released soon to avoid such workarounds :grimacing:

**Comment by viperfx** [comment]
Is there a fix available for gatsby?

**Comment by SaschaHeyer** [comment]
Is there a fix available for next.js?

**Comment by archywillhe** [comment]
@SaschaHeyer I managed to fix it by turning off `focus-within-pseudo-class'` in postcss-preset-env

```
module.exports = {
  plugins: [
    "tailwindcss",
    ["postcss-preset-env",{
      stage: 1,
      features: {
        'focus-within-pseudo-class': false
      }
    }],
  ]
};
``` 

Similiar to the nuxt fix but just have to follow nextjs's convention

**Comment by simonswiss** [comment]
Moving this into our GitHub Community Discussions, as it could be useful to many people, and could benefit from more visibility 👍
